language: python
python: 3.7

env:
  global:
    - CC_TEST_REPORTER_ID=e7f7a749f8f7c45fe806a0bdd90af45a9258f8b2d1f731cff794217b36314ed9

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install: make

before_install:
  - pip3 install poetry

install:
  - make install

script:
  - make lint
  - make coverage-xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false