language: python
python: 3.7

env:
  global:
    - CC_TEST_REPORTER_ID=59bae4c9ac57d9ecc31b3b5cb835c42cf75db87ea59b6be6c57c2f9af06ab65a

install: make

before_install:
  - pip3 install poetry

install:
  - make install

script:
  - make lint
  - make test-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false